#!/bin/sh

#
# Simple init script *sh compatible. Tested on Void Linux
#

# filesystems
mount -vt efivarfs efivarfs /sys/firmware/efi/efivars -o rw,relatime # If you use efi
# swapon /swapfile # for swap

# udevd to manage new connected devices
udevd --daemon
udevadm trigger --action=add --type=subsystems 
udevadm trigger --action=add --type=devices
udevadm settle

# dbus (many programs use this)
install -m755 -g 22 -o 22 -d /run/dbus
dbus-daemon --system --fork --nopidfile

# network
echo localhost > /proc/sys/kernel/hostname
dhcpcd
/usr/libexec/iwd >/dev/null 2>/dev/null &
ip a add 127.0.0.1/8 dev lo                # Connect to localhost should not work without it
ip link set dev lo up                      # Connect to localhost should not work without it

# Uncomment if bluez installed
# /usr/libexec/bluetooth/bluetoothd >/dev/null 2>/dev/null &

# Setup ttys 1..12
for i in $(seq 1 12); do
  while :; do
    setsid -c su - root <> /dev/tty$i >&0 2>&1
    # You can use login instead (not true way)
    # setsid -c login <> /dev/tty$i >&0 2>&1
  done &
done

# init communication
# You can delete this code but replace it with any blocking operation such as while true or cat
mkdir /run/init
mkfifo /run/init/communication

while :; do
  CMD=`cat /run/init/communication`

  case "$CMD" in
    "reboot" | "poweroff")
      pkill --inverse -f login -15 # SIGTERM all
      sleep 1
      pkill --inverse -f login -9  # SIGKILL all

      sync

      # Uncomment if you use network filesystem
      # umount -alt nfs
      # umount -alt nfs4

      # swapoff /swapfile # For swap

      # Uncomment if you need to stop HDDs before shutdown. Requires hd-idle
      # for i in /dev/sd?; do
      #   hd-idle -t $(basename "$i")
      # done

      timeout 2 umount -a
      ;;
  esac

  case "$CMD" in
    "reboot")
        echo b > /proc/sysrq-trigger
        cat # pause while. /run unmounted. /run/init/communication does not exist
      ;;
      "poweroff")
        echo o > /proc/sysrq-trigger
        cat # pause while. /run unmounted. /run/init/communication does not exist
      ;;
  esac
done >/dev/null 2>/dev/null
