#!/bin/sh

# Simple area screenshooter
# Requires scrot, slop, xclip
#

path=$HOME/Screenshots/$(date +"%Y-%m-%d_%N").png
scrot -a `slop -f "%x,%y,%w,%h"` -F "$path" && xclip -sel clip -t image/png "$path"
